[project]
name = "mcp-server-waktu-solat"
version = "0.1.0"
description = "Malaysia Prayer Time MCP Server"
authors = []
dependencies = [
    "requests>=2.31.0",
    "pydantic>=2.6.0"
]
requires-python = ">=3.9"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
